# Generated by Django 5.0.2 on 2024-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
